name: login_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fluentui_system_icons: ^1.1.270
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  path_provider:
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.3.1
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.2
  hydrated_bloc: ^10.0.0
  get_it: ^8.0.3
  injectable: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
