// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpk5R0FkPhH4-6UViSNwkIl603d3BK8Q',
    appId: '1:894143328797:web:63fda34f0f148a2f144cf4',
    messagingSenderId: '894143328797',
    projectId: 'login-system-725fb',
    authDomain: 'login-system-725fb.firebaseapp.com',
    storageBucket: 'login-system-725fb.firebasestorage.app',
    measurementId: 'G-6NGNQXQ4EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFCVtNyedVKtjMHnZLoVO9o3CFoemE5k',
    appId: '1:894143328797:android:a716f16fa7d6b996144cf4',
    messagingSenderId: '894143328797',
    projectId: 'login-system-725fb',
    storageBucket: 'login-system-725fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgHVlbk_YhaZ-V7NSzK5yDKntmdF5vdM',
    appId: '1:894143328797:ios:0495fa067e260b47144cf4',
    messagingSenderId: '894143328797',
    projectId: 'login-system-725fb',
    storageBucket: 'login-system-725fb.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgHVlbk_YhaZ-V7NSzK5yDKntmdF5vdM',
    appId: '1:894143328797:ios:0495fa067e260b47144cf4',
    messagingSenderId: '894143328797',
    projectId: 'login-system-725fb',
    storageBucket: 'login-system-725fb.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpk5R0FkPhH4-6UViSNwkIl603d3BK8Q',
    appId: '1:894143328797:web:aefc6bef4844ef18144cf4',
    messagingSenderId: '894143328797',
    projectId: 'login-system-725fb',
    authDomain: 'login-system-725fb.firebaseapp.com',
    storageBucket: 'login-system-725fb.firebasestorage.app',
    measurementId: 'G-09B1318W8J',
  );
}
